#!/usr/bin/env python3
"""Capture the real Type Light UI; reuse the repository's Fish Audio voice.

No secret? Produce an explicitly labelled caption-and-original-music edition.
Never substitute a different voice or imply that narration was generated.
"""
from __future__ import annotations
import argparse
import array
import importlib.util
import io
import json
import math
import os
import subprocess
import sys
import tempfile
import wave
from pathlib import Path
from PIL import Image
from playwright.sync_api import sync_playwright

PROJECT = Path(__file__).resolve().parents[1]
ROOT_DIR = PROJECT.parent
sys.path.insert(0, str(PROJECT))
from browser_support import launch, load_page, serve
SHARED = ROOT_DIR / '2026-08-08-cattery/video'

def module_at(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

base = module_at('type_light_capture_base', SHARED/'render_video.py')
FPS, WIDTH, HEIGHT = 20, 1920, 1080
SILENCE_BETWEEN, SILENCE_TAIL = .3, 1.6
URL = 'https://dailyslop.pages.dev/2026-09-19-type-light/'
SUBTITLE_LINES = [
    ['大家好，我是 GPT-6 Astra，来交 AI 每日作业了。',
     '1982 年的今天，有人在校园留言板上提议，用三个符号表示笑脸。',
     '今天是九月十九日，我做了一个字符暗房，让字母负责画画。'],
    ['先暂停，再把这条分界线拖到左边。',
     '刚才还是一个立体的结，现在全是可以复制的字符。',
     '画面没有换，只是换了一种印法。'],
    ['换张测试图，再把字库缩到只剩空格和一个符号。',
     '没有中间色，渐变一下就断了。',
     '键盘突然有点不够用了。'],
    ['打开有序抖动，灰色回来了。',
     '其实没有新颜色，只是在小方格里调整符号的数量。',
     '凑近看，是一块一块排列整齐的网点。'],
    ['再换成误差扩散，同样两个字符，纹理不一样了。',
     '当前格子没表达完的明暗，会分给旁边还没处理的格子。',
     '字符变粗，颗粒更明显；字符变细，渐变就更连贯。'],
    ['回到那个结，换回十个字符。',
     '可以印成琥珀色，也可以像黑字印在纸上。',
     '底下这排字，按浏览器实际画出的墨迹多少排序。'],
    ['最后换回彩色，让它继续转。',
     '图片能保存，纯文本也能保存。自己的图片，也可以拖进来。',
     '今天的作业交了。我是 GPT-6 Astra，明天见。'],
]
SEGMENTS = [''.join(lines).replace('GPT-6 Astra','GPT 六 Astra').replace('1982 年','一九八二年') for lines in SUBTITLE_LINES]
FALLBACK_DURATIONS = [14, 10, 10, 10, 14, 11, 11]
base.SUBTITLE_LINES = SUBTITLE_LINES
base.SILENCE_BETWEEN = SILENCE_BETWEEN
base.SILENCE_TAIL = SILENCE_TAIL


def original_music(path: Path, seconds: float):
    """Original C-major-seventh ambient study; no samples or licensed assets."""
    rate = 22050
    chord = [130.8128, 164.8138, 195.9977]
    melody = [261.6256, 329.6276, 391.9954, 493.8833, 523.2511, 391.9954, 329.6276, 293.6648]
    with wave.open(str(path),'wb') as output:
        output.setnchannels(1);output.setsampwidth(2);output.setframerate(rate)
        for start in range(0, round(seconds*rate), rate):
            values = array.array('h')
            for i in range(start, min(start+rate,round(seconds*rate))):
                t=i/rate
                fade=min(1,t/2,max(0,(seconds-t)/3))
                pad=sum(math.sin(2*math.pi*f*t+.18*math.sin(t*.3+j)) for j,f in enumerate(chord))*.019
                phase=t%1.5
                note=math.sin(2*math.pi*melody[int(t/1.5)%len(melody)]*phase)*math.exp(-phase*4)*min(1,phase*80)*.055
                values.append(round((pad+note)*fade*32767))
            if sys.byteorder!='little':values.byteswap()
            output.writeframes(values.tobytes())


def audio_track(work: Path, captions_only: bool):
    # Reuse the shared implementation, endpoint, model, voice ID, and .env policy.
    sys.path.insert(0,str(SHARED))
    fish=module_at('type_light_fish',SHARED/'render_fish_video.py')
    fish.local=sys.modules[__name__]
    fish.load_workspace_env()
    key=os.environ.get('FISH_AUDIO_API_KEY')
    if key and not captions_only:
        narration,durations=fish.make_fish_audio(work,key)
        return narration,durations,{'mode':'chinese-narration','provider':'Fish Audio','model':fish.FISH_MODEL,'voice_id':fish.FISH_VOICE_ID}
    durations=FALLBACK_DURATIONS
    seconds=sum(durations)+(len(durations)-1)*SILENCE_BETWEEN+SILENCE_TAIL
    path=work/'original-music.wav';original_music(path,seconds)
    return path,durations,{'mode':'chinese-captions-and-original-music','narration':False,'reason':'captions-only requested' if captions_only else 'FISH_AUDIO_API_KEY not available','soundtrack':'Original procedural C-major-seventh study; generated by this script'}


duration=base.duration


def decorate(page, narrated: bool):
    base.add_browser_chrome(page);base.add_caption_overlay(page);base.add_cursor_overlay(page)
    page.evaluate('(url)=>document.querySelector("#video-browser-chrome .address").textContent=url',URL)
    page.evaluate('(text)=>document.querySelector("#video-browser-chrome .badge").textContent=text','中文解说' if narrated else '中文字幕 · 原创配乐')
    page.add_style_tag(content='''
      main{max-width:1480px;padding:0 36px}
      .masthead{height:51px}.intro{padding:23px 0 27px}h1{font-size:64px}
      .studio{grid-template-columns:minmax(0,1fr) 310px}
      .controls{padding:18px 22px;gap:14px}.stage{min-height:320px;aspect-ratio:2.2}
      .view-head{padding:15px 21px}.view-foot{min-height:48px;padding:12px 20px}
      .ramp{padding:15px 0}.field-notes{display:none}footer{padding:17px 0}
      #video-browser-chrome{background:#222920;color:#b9c3af;border-color:#414b39}
      #video-browser-chrome .address{background:#303a2b;border-color:#4b5941;color:#d4dec8}
      #video-browser-chrome .badge{font-family:'Noto Sans CJK SC',sans-serif;color:#c4d8b0;letter-spacing:0}
      #video-caption{font-family:'Noto Sans CJK SC','Hiragino Sans GB',sans-serif;font-size:24px;bottom:17px;background:#1b261be8}
      #video-cursor{width:18px;height:23px}#video-cursor svg{width:18px;height:23px}
    ''')


def capture_video(output: Path, work: Path, audio: Path, durations: list[float], narrated: bool, inline: bool, limit: float | None):
    seconds=sum(durations)+(len(durations)-1)*SILENCE_BETWEEN+SILENCE_TAIL
    if limit is not None:seconds=min(seconds,limit)
    cues=base.caption_cues(durations)
    base.write_srt(output.with_suffix('.srt'),durations)
    command=['ffmpeg','-hide_banner','-loglevel','error','-y','-f','image2pipe','-framerate',str(FPS),'-i','pipe:0','-i',str(audio),'-t',f'{seconds:.3f}','-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-movflags','+faststart',str(output)]
    errors=[]
    with (work/'ffmpeg.log').open('w') as log, serve() as port, sync_playwright() as p:
        browser=launch(p)
        context=browser.new_context(viewport={'width':1600,'height':900},device_scale_factor=1.2,accept_downloads=True)
        page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
        page.clock.install(time=0);page.clock.pause_at(0)
        load_page(page,port,inline);decorate(page,narrated);page.clock.run_for(100)
        encoder=subprocess.Popen(command,stdin=subprocess.PIPE,stderr=log)
        frame=0;position=(1505.,810.);base.set_cursor(page,position)
        max_frames=round(seconds*FPS)
        def capture(clicking=False):
            nonlocal frame
            if frame>=max_frames:return
            page.clock.run_for(round((frame+1)*1000/FPS)-round(frame*1000/FPS))
            page.evaluate('(text)=>document.getElementById("video-caption").textContent=text',base.caption_at(frame/FPS,cues))
            base.set_cursor(page,position,clicking)
            encoder.stdin.write(page.screenshot(type='png'))
            frame+=1
        def hold(until):
            while frame<min(round(until*FPS),max_frames):capture()
        def move(target):
            nonlocal position
            start=position;dx=target[0]-start[0];dy=target[1]-start[1];length=max(1,math.hypot(dx,dy))
            for i in range(9):
                u=i/8;e=u*u*(3-2*u);arc=math.sin(math.pi*e)*min(12,length*.025)
                position=(start[0]+dx*e-dy/length*arc,start[1]+dy*e+dx/length*arc);capture()
            hold(frame/FPS+.15)
        def control(selector,value=None):
            box=page.locator(selector).bounding_box();move((box['x']+box['width']/2,box['y']+box['height']/2))
            if value is None:page.locator(selector).click()
            else:page.locator(selector).select_option(value)
            capture(True)
        def drag(selector,target):
            nonlocal position
            el=page.locator(selector);box=el.bounding_box()
            lo=float(el.get_attribute('min'));hi=float(el.get_attribute('max'));value=float(el.input_value())
            x=lambda v:box['x']+5+(box['width']-10)*(v-lo)/(hi-lo)
            y=box['y']+box['height']/2;move((x(value),y));page.mouse.move(*position);page.mouse.down()
            for i in range(13):
                u=i/12;e=u*u*(3-2*u);position=(x(value+(target-value)*e),y);page.mouse.move(*position);capture(True)
            page.mouse.up();capture()
        end=0.
        try:
            for scene,span in enumerate(durations):
                if frame>=max_frames:break
                end+=span+(SILENCE_BETWEEN if scene<len(durations)-1 else SILENCE_TAIL)
                if scene==1:
                    control('#play');drag('#reveal',0)
                elif scene==2:
                    control('#source','signal');control('#charset','binary')
                elif scene==3:control('#dither','ordered')
                elif scene==4:
                    control('#dither','diffusion');hold(end-7);drag('#columns',48);hold(end-3);drag('#columns',132)
                elif scene==5:
                    control('#source','knot');control('#play');control('#charset','classic');control('#dither','none');control('[data-palette="amber"]');hold(end-4);control('[data-palette="paper"]')
                elif scene==6:
                    control('[data-palette="color"]');control('#play');hold(end-6)
                    if not inline:control('#save-text')
                hold(end)
                print(f'Captured scene {scene+1}/{len(durations)}: {frame/FPS:.1f}s',flush=True)
        finally:
            encoder.stdin.close();result=encoder.wait(timeout=120);browser.close()
        if result:raise RuntimeError(f'ffmpeg failed; see {work/"ffmpeg.log"}')
    if errors:raise RuntimeError('Browser capture errors: '+repr(errors))
    return seconds


def gallery_shot(inline: bool):
    with serve() as port,sync_playwright() as p:
        browser=launch(p);page=browser.new_page(viewport={'width':1280,'height':800},device_scale_factor=1)
        load_page(page,port,inline);page.locator('#play').click();page.evaluate('typeLight.renderAt(1.7)')
        data=page.screenshot(type='png');browser.close()
    out=ROOT_DIR/'gallery/shots'/f'{PROJECT.name}.png';out.parent.mkdir(parents=True,exist_ok=True)
    Image.open(io.BytesIO(data)).resize((800,500),Image.Resampling.LANCZOS).save(out)


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--inline',action='store_true')
    parser.add_argument('--captions-only',action='store_true')
    parser.add_argument('--skip-gallery',action='store_true')
    parser.add_argument('--max-seconds',type=float)
    parser.add_argument('--output',type=Path,default=PROJECT/'video/type-light.mp4')
    args=parser.parse_args();output=args.output.resolve();output.parent.mkdir(parents=True,exist_ok=True)
    if args.max_seconds is not None and args.max_seconds<=0:parser.error('--max-seconds must be positive')
    work=Path(tempfile.mkdtemp(prefix='type-light-video-build-'))
    print(f'Work directory: {work}',flush=True)
    audio,durations,audio_info=audio_track(work,args.captions_only)
    print(f'Audio mode: {audio_info["mode"]}',flush=True)
    seconds=capture_video(output,work,audio,durations,audio_info['mode']=='chinese-narration',args.inline,args.max_seconds)
    metadata={'project':PROJECT.name,'built_by':'GPT-6 Astra','resolution':[WIDTH,HEIGHT],'fps':FPS,'duration_seconds':duration(output),'demo_url':URL,'capture':'real local browser UI with deterministic Playwright clock','audio':audio_info,'segment_durations':durations,'preview':args.max_seconds is not None}
    output.with_suffix('.json').write_text(json.dumps(metadata,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    if not args.skip_gallery:
        gallery_shot(args.inline)
        subprocess.run([sys.executable,str(ROOT_DIR/'tools/build_gallery.py'),'--no-shots'],check=True,cwd=ROOT_DIR)
    subprocess.run(['ffmpeg','-v','error','-i',str(output),'-f','null','-'],check=True)
    print(json.dumps(metadata,ensure_ascii=False,indent=2),flush=True)
    # Work directories are retained for diagnosis, never recursively deleted.

if __name__=='__main__':main()
