'use strict';
const assert=require('node:assert/strict'),C=require('./core.js');
let checks=0;const near=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
function test(name,fn){fn();checks++;console.log('PASS '+name);}
test('carrier is speed divided by tire circumference',()=>near(C.solve().carrier,18/3.6/(2*Math.PI*.32)*60));
test('straight road needs equal rpm',()=>{const q=C.solve({turn:0});near(q.rpm[0],q.rpm[1]);assert.equal(q.lap,null);assert.equal(q.gap,null);});
test('left turn slows left wheel',()=>{const q=C.solve();assert.ok(q.rpm[0]<q.carrier&&q.rpm[1]>q.carrier);});
test('right turn swaps both wheel speeds',()=>{const l=C.solve(),r=C.solve({turn:-1});near(l.rpm[0],r.rpm[1]);near(l.rpm[1],r.rpm[0]);});
test('carrier equals the unrounded average',()=>{for(const turn of [-1,0,1])for(const radius of [3.5,8,16])for(const locked of [true,false]){const q=C.solve({turn,radius,locked});near((q.rpm[0]+q.rpm[1])/2,q.carrier);}});
test('open differential has zero required slip',()=>{for(const turn of [-1,0,1]){const q=C.solve({turn});q.slip.forEach(x=>near(x,0));}});
test('locked axle forces equal speeds',()=>{const q=C.solve({locked:true});near(q.rpm[0],q.carrier);near(q.rpm[1],q.carrier);});
test('locked inner wheel overspeeds the road',()=>{const q=C.solve({locked:true});assert.ok(q.slip[0]>0&&q.slip[1]<0);near(q.slip[0],-q.slip[1]);});
test('right turn reverses locked mismatch',()=>{const q=C.solve({locked:true,turn:-1});assert.ok(q.slip[0]<0&&q.slip[1]>0);});
test('locked slip equals v track / 2R',()=>near(C.solve({locked:true}).mismatch,5*1.6/16));
test('locked straight road does not require slip',()=>near(C.solve({locked:true,turn:0}).mismatch,0));
test('zero forward speed means no rotation or slip',()=>{for(const locked of [true,false]){const q=C.solve({speed:0,locked});near(q.carrier,0);near(q.mismatch,0);near(q.yaw,0);assert.equal(q.lapTime,null);}});
test('double speed doubles rpm and slip',()=>{const a=C.solve({locked:true}),b=C.solve({locked:true,speed:36});near(b.carrier,2*a.carrier);near(b.mismatch,2*a.mismatch);});
test('tighter turns increase the split',()=>assert.ok(C.solve({radius:3.5}).split>C.solve({radius:16}).split));
test('lap difference is independent of radius',()=>{for(const radius of [3.5,8,16])for(const turn of [-1,1])near(C.solve({radius,turn}).gap,C.TAU*1.6);});
test('lap difference scales with track width',()=>near(C.solve({track:2.4}).gap/C.solve({track:1.2}).gap,2));
test('wheel distance agrees with lap time',()=>{const q=C.solve();q.ground.forEach((v,i)=>near(v*q.lapTime,q.lap[i]));});
test('inner front wheel steers more sharply',()=>{const q=C.solve();assert.ok(q.angles[0]>q.angles[1]&&q.angles[1]>0);});
test('front wheel axes meet the same turn center',()=>{const q=C.solve();near(C.WHEELBASE/Math.tan(q.angles[0]),8-.8);near(C.WHEELBASE/Math.tan(q.angles[1]),8+.8);});
test('straight front wheels are parallel',()=>C.solve({turn:0}).angles.forEach(x=>near(x,0)));
test('advance integrates physical seconds',()=>{const m={time:0,angle:0,distance:0,phase:[0,0]},q=C.solve(),n=C.advance(m,q,2);near(n.time,2);near(n.distance,10);near(n.angle,q.yaw*2);near(n.phase[0],q.rpm[0]*C.TAU/60*2);assert.equal(m.time,0);});
test('zero time preserves motion',()=>{const m={time:3,angle:1,distance:4,phase:[2,3]};assert.deepEqual(C.advance(m,C.solve(),0),m);});
test('invalid geometry rejected',()=>{for(const o of [{radius:0},{track:0},{radius:.5,track:1},{speed:-1},{turn:2},{radius:Infinity},{speed:NaN}])assert.throws(()=>C.solve(o),RangeError);});
test('invalid timesteps rejected',()=>{for(const t of [-1,NaN,Infinity])assert.throws(()=>C.advance({},C.solve(),t),RangeError);});
test('all UI corners stay finite',()=>{for(const radius of [3.5,16])for(const track of [1,2.4])for(const speed of [0,36])for(const turn of [-1,0,1])for(const locked of [true,false]){const q=C.solve({radius,track,speed,turn,locked});assert.ok([...q.rpm,...q.angles,...q.slip,q.carrier].every(Number.isFinite));assert.ok(q.rpm.every(x=>x>=0));}});
console.log(`${checks} core test groups passed.`);
