'use strict';
const assert=require('node:assert/strict'),C=require('./core.js');
let passed=0;const test=(name,fn)=>{fn();passed++;console.log(`ok ${passed} - ${name}`);};
const near=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
const s=C.sanitize(C.PRESETS.gallery),p=C.paths(s),by=id=>p.find(x=>x.id===id),len=pts=>pts.slice(1).reduce((n,b,i)=>n+Math.hypot(b.x-pts[i].x,b.y-pts[i].y),0);
test('default geometry is bounded',()=>{assert.equal(s.width,14);assert.equal(s.depth,9);assert.equal(s.absorption,.16);});
test('presets are copied, not mutated',()=>{const v=C.sanitize(C.PRESETS.studio);v.source.x=10;assert.equal(C.PRESETS.studio.source.x,1.5);});
test('invalid numerical inputs fall back or clamp',()=>{const v=C.sanitize({width:NaN,depth:99,absorption:-7,source:{x:-9,y:Infinity}});assert.equal(v.width,14);assert.equal(v.depth,16);assert.equal(v.absorption,0);assert.equal(v.source.x,.2);});
test('221 Manhattan-order images at order ten',()=>assert.equal(p.length,221));
test('every image has a unique id',()=>assert.equal(new Set(p.map(x=>x.id)).size,p.length));
test('direct path and distance',()=>{assert.equal(by('0,0').order,0);near(by('0,0').length,Math.hypot(7.3,1.9));});
test('west first image has analytic length',()=>near(by('-1,0').length,Math.hypot(s.source.x+s.listener.x,s.source.y-s.listener.y)));
test('east first image has analytic length',()=>near(by('1,0').length,Math.hypot(2*s.width-s.source.x-s.listener.x,s.source.y-s.listener.y)));
test('north first image has analytic length',()=>near(by('0,-1').length,Math.hypot(s.source.x-s.listener.x,s.source.y+s.listener.y)));
test('south first image has analytic length',()=>near(by('0,1').length,Math.hypot(s.source.x-s.listener.x,2*s.depth-s.source.y-s.listener.y)));
test('arrival times are sorted and nonnegative',()=>p.forEach((v,i)=>assert.ok(v.delay>=0&&(!i||v.delay>=p[i-1].delay))));
test('folded ray lengths equal unfolded lengths',()=>p.forEach(v=>near(len(v.points),v.length)));
test('all bounce counts match the geometry',()=>p.forEach(v=>{assert.equal(v.points.length,v.order+2);assert.equal(v.walls.length,v.order);}));
test('all folded points lie in the room',()=>p.forEach(v=>v.points.forEach(q=>assert.ok(q.x>=-1e-9&&q.x<=s.width+1e-9&&q.y>=-1e-9&&q.y<=s.depth+1e-9))));
test('every specular reflection obeys equal angles',()=>p.forEach(v=>v.points.slice(1,-1).forEach((q,i)=>{
 const a=v.points[i],b=v.points[i+2],u={x:q.x-a.x,y:q.y-a.y},w={x:b.x-q.x,y:b.y-q.y},n=Math.hypot(u.x,u.y),m=Math.hypot(w.x,w.y);
 if(['east','west'].includes(v.walls[i])){near(u.x/n,-w.x/m);near(u.y/n,w.y/m);}else{near(u.y/n,-w.y/m);near(u.x/n,w.x/m);}
})));
test('travel time uses 343 metres per second',()=>p.forEach(v=>near(v.delay,v.length/343)));
test('energy absorption uses its square root in pressure',()=>near(by('-1,0').gain,Math.sqrt(.84)/by('-1,0').length));
test('multiple reflections multiply pressure factors',()=>near(by('3,-2').gain,Math.sqrt(.84)**5/by('3,-2').length));
test('absorption changes gain but not geometry or timing',()=>{const high=C.paths({...s,absorption:.9});high.forEach((v,i)=>{near(v.delay,p[i].delay);assert.ok(v.gain<=p[i].gain+1e-12);});});
test('fully absorbing walls leave only direct sound',()=>{const all=C.paths({...s,absorption:1});all.forEach(v=>v.order?assert.equal(v.gain,0):assert.ok(v.gain>0));assert.deepEqual(C.synthesize(all),C.synthesize(all,'room'));const a=C.synthesize(all),d=C.synthesize(all,'direct');for(let i=0;i<a.length;i++)near(a[i],d[i]||0);});
test('lossless walls retain inverse-distance spreading',()=>C.paths({...s,absorption:0}).forEach(v=>near(v.gain,1/Math.max(1,v.length))));
test('source/listener reciprocity preserves delays and gains',()=>{const reverse=C.paths({...s,source:s.listener,listener:s.source});assert.equal(reverse.length,p.length);reverse.forEach((v,i)=>{near(v.delay,p[i].delay);near(v.gain,p[i].gain);});});
test('scaling room scales delays, not bounce counts',()=>{const k=1.4,m=C.paths({...s,width:s.width*k,depth:s.depth*k,source:{x:s.source.x*k,y:s.source.y*k},listener:{x:s.listener.x*k,y:s.listener.y*k}});m.forEach((v,i)=>{near(v.delay,p[i].delay*k);near(v.gain,p[i].gain/k);});});
test('corner hits are omitted explicitly',()=>assert.equal(C.trace(C.sanitize({width:8,depth:8,source:{x:2,y:2},listener:{x:6,y:6}}),-1,-1),null));
test('coincident points and near-wall cases stay finite',()=>{for(const t of [{...s,listener:s.source},{width:4,depth:3,source:{x:0,y:0},listener:{x:4,y:3},absorption:0}])for(const v of C.paths(t))assert.ok(Number.isFinite(v.gain)&&Number.isFinite(v.delay));});
test('orders zero, one and two give expected image counts',()=>{assert.equal(C.paths(s,0).length,1);assert.equal(C.paths(s,1).length,5);assert.equal(C.paths(s,2).length,13);});
test('moving a pulse follows path endpoints',()=>{for(const v of p){assert.deepEqual(C.atDistance(v,0),v.points[0]);const end=C.atDistance(v,v.length+1);assert.deepEqual(end,v.points.at(-1));}});
test('deterministic pulse synthesis and bounded samples',()=>{const a=C.synthesize(p);assert.deepEqual(a,C.synthesize(p));assert.ok(a.some(x=>Math.abs(x)>.01));for(const v of a)assert.ok(Number.isFinite(v)&&Math.abs(v)<=1);assert.throws(()=>C.synthesize(p,'room',0),RangeError);});
test('audio is silent before direct arrival and contains echoes',()=>{const a=C.synthesize(p),d=C.synthesize(p,'direct'),start=Math.floor(by('0,0').delay*44100);for(let i=0;i<start;i++)assert.equal(a[i],0);assert.ok(a.slice(d.length).some(x=>Math.abs(x)>1e-6));});
test('WAV header, sample rate and sizes are valid',()=>{const a=C.synthesize(p),b=C.wav(a),v=new DataView(b);assert.equal(Buffer.from(b,0,4).toString(),'RIFF');assert.equal(v.getUint32(24,true),44100);assert.equal(v.getUint32(40,true),a.length*2);assert.equal(b.byteLength,44+a.length*2);});
test('randomized geometry stress: finite rays and equal lengths',()=>{let seed=981;const r=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);for(let n=0;n<100;n++){const w=4+r()*26,d=3+r()*13,t=C.sanitize({width:w,depth:d,absorption:r(),source:{x:.2+r()*(w-.4),y:.2+r()*(d-.4)},listener:{x:.2+r()*(w-.4),y:.2+r()*(d-.4)}});for(const q of C.paths(t)){near(len(q.points),q.length,1e-7);assert.ok(Number.isFinite(q.gain));}}});
console.log(JSON.stringify({core_test_groups:passed,status:'passed'}));
